[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SERVER_URL = "https://metaverse-backend.onrender.com"
  VITE_APP_NAME = "Metaverse"
  VITE_APP_VERSION = "2.0.0"
  NODE_ENV = "production"
  VITE_ENVIRONMENT = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific configurations
[context.production.environment]
  VITE_SERVER_URL = "https://metaverse-backend.onrender.com"
  VITE_ENVIRONMENT = "production"

[context.staging.environment]
  VITE_SERVER_URL = "https://metaverse-backend-staging.onrender.com"
  VITE_ENVIRONMENT = "staging"

[context.deploy-preview.environment]
  VITE_SERVER_URL = "https://metaverse-backend-dev.onrender.com"
  VITE_ENVIRONMENT = "preview" 