[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  FORCE_DEPLOY = "true"
  VERSION = "2.1.0"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    X-Version = "2.1.0"
    X-Cache-Bust = "true"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    X-Version = "2.1.0"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    X-Version = "2.1.0"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    X-Version = "2.1.0"

# Force fresh deployment
[context.production.environment]
  FORCE_DEPLOY = "true"
  VERSION = "2.1.0"
  CACHE_BUST = "true"

# Redirects to force fresh loading
[[redirects]]
  from = "/"
  to = "/?v=2.1.0&cb=true"
  status = 302
  force = true 