[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SERVER_URL = "https://metaverse-project-2.onrender.com"
  VITE_APP_NAME = "Metaverse"
  VITE_APP_VERSION = "2.0.0"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 